export const INSURANCE_PLANS = [
  {
    id: 1,
    title: 'Защита здоровья ПЛЮС',
    minDuration: 12,
    maxDuration: 24,
    premium: 2000,
    sum: 200000,
    minBodyMassIndex: 18,
    maxBodyMassIndex: 25,
    minAge: 18,
    maxAge: 65,
    risks: [
      'Смерть по любой причине',
      'Инвалидность I, II, или III степени по любой причине',
    ],
  },
  {
    id: 2,
    title: 'Защита здоровья ПЛЮС +',
    minDuration: 12,
    maxDuration: 24,
    premium: 2400,
    sum: 200000,
    minBodyMassIndex: 25,
    maxBodyMassIndex: 35,
    minAge: 18,
    maxAge: 65,
    risks: [
      'Смерть по любой причине',
      'Инвалидность I, II, или III степени по любой причине',
    ],
  },
  {
    id: 3,
    title: 'Защита здоровья',
    minDuration: 12,
    maxDuration: 24,
    premium: 1000,
    sum: 100000,
    minBodyMassIndex: 18,
    maxBodyMassIndex: 25,
    minAge: 18,
    maxAge: 65,
    risks: [
      'Смерть в результате несчастного случая',
      'Инвалидность I, II, или III степени в результате несчастного случая',
    ],
  },
  {
    id: 4,
    title: 'Защита здоровья +',
    minDuration: 12,
    maxDuration: 24,
    premium: 1200,
    sum: 100000,
    minBodyMassIndex: 25,
    maxBodyMassIndex: 35,
    minAge: 18,
    maxAge: 65,
    risks: [
      'Смерть в результате несчастного случая',
      'Инвалидность I, II, или III степени в результате несчастного случая',
    ],
  },
];
